site:
  domain: http://youkechuang.cn
  title: 尤科闯的官方网站
  description: 尤科闯的官方网站 (liaoxuefeng.com) 研究互联网产品和技术，提供原创中文精品教程
  keywords: 尤科闯, liaoxuefeng, git, gitsite, javascript, node, jquery, python, java, spring, sql, database, linux, operating system, os, cpu, verilog, risc-v, bitcoin, ethereum, ai, 教程, 软件, 编程, 开发, 运维, 云计算, 网络, 互联网, 比特币, 以太坊, 操作系统, 智能合约, 数字货币
  theme: default
  language: zh-CN
  # set the /<rootPath> pathname under which your site is served
  # for GitHub pages deployment without a custom domain, it is often '/<projectName>'
  # root-path: /gitsite
  # set cdn prefix: self hosted
  cdn-path: /static
  navigation:
    - title: 我是谁
      uri: /books/whoami/index.html
    - title: Python教程
      uri: /books/python/index.html
    - title: 我的1/3人生
      uri: /books/onethird/index.html
    - title: 博客
      uri: /blogs/all/index.html
  git:
    base-url: https://github.com/youkechaung/liaoxuefeng.com/blob/main/source
  contact:
    name: George You
    github: https://github.com/youkechaung/youkechuang.cn
    twitter: https://twitter.com/GeorgeYoukc
  books:
    index-marker: true
  search:
    # none = no search
    # browser = flex search in browser
    # google = google site search
    type: browser
  # control styles:
  styles:
    # show 'Edit in Git':
    display-git-link: false
    # any custom styles used in theme:
    # code-font: Monaco
  integration:
    comment:
      provider: oauth
      url: https://api.liaoxuefeng.com
    analytics:
      provider: baidu
      id: "2efddd14a5f2b304677462d06fb4f964"
  footer: |
          <div>
            &copy;<a href="/">youkechuang.cn</a> 
            - <a href="https://weibo.com/youkc" target="_blank">微博</a>
            - <a href="https://github.com/youkechaung/youkechuang.cn" target="_blank">GitHub</a>
            - <a href="/pages/license/index.html" target="_blank">License</a>
          </div>


build:
  # copy special files under root dir (ignore if not found):
  copy:
    - favicon.ico
    - robots.txt
    - ads.txt

# you can add any items:
